# docker-compose.yml

version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hello_world_db
      POSTGRES_USER: hello_user
      POSTGRES_PASSWORD: hello_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=hello_world_db
      - DB_USER=hello_user
      - DB_PASSWORD=hello_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
